<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/VerbaCore/VerbaCore.csproj" />
    <None Include="../../src/VerbaCore/App.xaml" Link="AppResources.xaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>